apiVersion: v1
kind: Pod
metadata:
  name: amani-nginx
  labels: 
     app: amani 
     touka: touka
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    