apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-amani 
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amani-amani
  template:
   metadata:
      name: nginx-nginx
      labels: 
        app: amani-amani
   spec:
     containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
         - containerPort: 80