apiVersion: v1
kind: Service
metadata:
  name: my-service-cluster
  labels:
    app: my-app
spec:
  type: ClusterIP
  selector:
    app: amani
    touka: touka
  ports:
    - protocol: TCP
      port: 80      # The port that will be exposed by the service
      targetPort: 8080  # The port on the pod that the traffic will be forwarded to














